services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:16
    container_name: postgresdb      # here to name the container itself for docker cli
    environment:
      POSTGRES_DB: task-managerdb   # name of the actual database, goes in spring.datasource.url
      POSTGRES_USER: task-manager-postgresql-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:   # environment tells the container running the app to use these to connect to DB.
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task-managerdb
      SPRING_DATASOURCE_USERNAME: task-manager-postgresql-db
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

volumes:
  postgres_data: