networks:
  public:
  observability:
  data:

services:

  lgtm:
    image: grafana/otel-lgtm
    networks:
      - observability
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=false
    restart: unless-stopped

  postgres:
    image: postgres:16
    networks:
      - data
    container_name: postgresdb
    environment:
      POSTGRES_DB: task-managerdb
      POSTGRES_USER: task-manager-postgresql-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U task-manager-postgresql-db -d task-managerdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    networks:
      - public
      - observability
      - data
    ports:
      - "8080:8080"
    environment:
      # ACTIVE PROFILE
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # DB CONFIG
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task-managerdb
      SPRING_DATASOURCE_USERNAME: task-manager-postgresql-db
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # JWT CONFIG
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # ADMIN CREDENTIALS
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD_BCRYPT: ${ADMIN_PASSWORD_BCRYPT}

      # REFRESH TOKEN
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      REFRESH_ABSOLUTE_EXPIRY: ${REFRESH_ABSOLUTE_EXPIRY}
    depends_on:
      postgres:
        condition: service_healthy
      lgtm:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data: