spring.application.name=task-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/meuapp
spring.datasource.username=postgres
spring.datasource.password=senha123

# this is crucial, tell hibernate to auto update tables in DB, but never in real apps. It should be 'validate', get to know about flyway afterward.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect