spring.application.name=task-manager

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Paging size
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=when-authorized

# 1.0 = trace every request. In prod. you'd use 0.1 (10%) to reduce overhead.
management.tracing.sampling.probability=0.1