spring.application.name=task-manager

spring.datasource.url=jdbc:postgresql://postgres:5432/task-managerdb
spring.datasource.username=task-manager-postgresql-db
spring.datasource.password=${DB_PASSWORD}

# Spring Data JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# JWT secret and expiration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS:84600000}

# Paging size
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=when-authorized

# tells Spring which profile to use - override per environment
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# 1.0 = trace every request. In prod. you'd use 0.1 (10%) to reduce overhead.
management.tracing.sampling.probability=0.1