CREATE TABLE refresh_tokens
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash          VARCHAR(64)                             NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    expires_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked             BOOLEAN                                 NOT NULL DEFAULT FALSE,
    absolute_expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uc_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);